// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokedexRazorPages.Data;

#nullable disable

namespace PokedexRazorPages.Migrations
{
    [DbContext(typeof(PokedexRazorPagesContext))]
    [Migration("20230823170617_super db test pt3")]
    partial class superdbtestpt3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokedexRazorPages.Models.Abilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_Hidden")
                        .HasColumnType("bit");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilitiesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AbilitiesId");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Animated", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Black_WhiteId")
                        .HasColumnType("int");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Black_WhiteId")
                        .IsUnique();

                    b.ToTable("Animated");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Black_White", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_vId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_vId")
                        .IsUnique();

                    b.ToTable("BlackWhite");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Crystal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_iiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_iiId")
                        .IsUnique();

                    b.ToTable("Crystal");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Diamond_Pearl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_ivId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_ivId")
                        .IsUnique();

                    b.ToTable("DiamondPearl");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.DreamWorld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OtherId")
                        .IsUnique();

                    b.ToTable("DreamWorld");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Emerald", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_iiiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_iiiId")
                        .IsUnique();

                    b.ToTable("Emerald");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Firered_Leafgreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_iiiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_iiiId")
                        .IsUnique();

                    b.ToTable("FireredLeafgreen");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Forms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Game_Indices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Game_Index")
                        .HasColumnType("int");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("GameIndices");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PastTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PastTypesId")
                        .IsUnique();

                    b.ToTable("Generation");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_i", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VersionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId")
                        .IsUnique();

                    b.ToTable("GenerationI");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_ii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VersionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId")
                        .IsUnique();

                    b.ToTable("GenerationII");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_iii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VersionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId")
                        .IsUnique();

                    b.ToTable("GenerationIII");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_iv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VersionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId")
                        .IsUnique();

                    b.ToTable("GenerationIV");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_v", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VersionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId")
                        .IsUnique();

                    b.ToTable("GenerationV");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_vi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VersionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId")
                        .IsUnique();

                    b.ToTable("GenerationVI");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_vii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VersionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId")
                        .IsUnique();

                    b.ToTable("GenerationVII");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_viii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VersionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId")
                        .IsUnique();

                    b.ToTable("GenerationVIII");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Gold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_iiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_iiId")
                        .IsUnique();

                    b.ToTable("Gold");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Heartgold_Soulsilver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_ivId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_ivId")
                        .IsUnique();

                    b.ToTable("HeartgoldSoulsilver");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Held_Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("HeldItems");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OtherId")
                        .IsUnique();

                    b.ToTable("Home");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Icons_vii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_viiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_viiId")
                        .IsUnique();

                    b.ToTable("Icons_vii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Icons_viii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_viiiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_viiiId")
                        .IsUnique();

                    b.ToTable("Icons_viii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Held_ItemsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Held_ItemsId")
                        .IsUnique();

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.ItemVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version_DetailsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Version_DetailsId")
                        .IsUnique();

                    b.ToTable("ItemVersion");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovesId")
                        .IsUnique();

                    b.ToTable("Move");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Move_Learn_Method", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version_Group_DetailsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Version_Group_DetailsId")
                        .IsUnique();

                    b.ToTable("MoveLearnMethod");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Moves", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Official_Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OtherId")
                        .IsUnique();

                    b.ToTable("OfficialArtwork");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Omegaruby_Alphasapphire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_viId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_viId")
                        .IsUnique();

                    b.ToTable("OmegarubyAlphasapphire");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Other", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SpritesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpritesId")
                        .IsUnique();

                    b.ToTable("Other");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.PastTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("TypesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TypesId");

                    b.ToTable("PastTypes");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Platinum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_ivId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_ivId")
                        .IsUnique();

                    b.ToTable("Platinum");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Base_Experience")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Location_Area_Encounters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Red_Blue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Gray")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Gray")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_iId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_iId")
                        .IsUnique();

                    b.ToTable("RedBlue");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Ruby_Sapphire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_iiiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_iiiId")
                        .IsUnique();

                    b.ToTable("RubySapphire");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Silver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_iiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_iiId")
                        .IsUnique();

                    b.ToTable("Silver");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId")
                        .IsUnique();

                    b.ToTable("Species");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Sprites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId")
                        .IsUnique();

                    b.ToTable("Sprites");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatsId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StatsId")
                        .IsUnique();

                    b.ToTable("Stat");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Base_Stat")
                        .HasColumnType("int");

                    b.Property<int>("Effort")
                        .HasColumnType("int");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("PokemondId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypesId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TypesId")
                        .IsUnique();

                    b.ToTable("Type");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Types", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Ultra_Sun_Ultra_Moon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_viiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_viiId")
                        .IsUnique();

                    b.ToTable("UltraSunUltraMoon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Game_IndicesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Game_IndicesId")
                        .IsUnique();

                    b.ToTable("Version");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Version_Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Held_ItemsId")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Held_ItemsId");

                    b.ToTable("VersionDetails");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Version_Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version_Group_DetailsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Version_Group_DetailsId")
                        .IsUnique();

                    b.ToTable("VersionGroup");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Version_Group_Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Level_Learned_At")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovesId");

                    b.ToTable("VersionGroupDetails");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Versions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SpritesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpritesId")
                        .IsUnique();

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.X_Y", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Shiny_Female")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_viId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_viId")
                        .IsUnique();

                    b.ToTable("XYs");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Yellow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Back_Gray")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front_Gray")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation_iId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Generation_iId")
                        .IsUnique();

                    b.ToTable("Yellow");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Abilities", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithMany("Abilities")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Ability", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Abilities", "Abilities")
                        .WithMany("Abilitys")
                        .HasForeignKey("AbilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abilities");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Animated", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Black_White", "Black_White")
                        .WithOne("Animated")
                        .HasForeignKey("PokedexRazorPages.Models.Animated", "Black_WhiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Black_White");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Black_White", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_v", "Generation_v")
                        .WithOne("Black_White")
                        .HasForeignKey("PokedexRazorPages.Models.Black_White", "Generation_vId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_v");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Crystal", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_ii", "Generation_ii")
                        .WithOne("Crystal")
                        .HasForeignKey("PokedexRazorPages.Models.Crystal", "Generation_iiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_ii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Diamond_Pearl", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_iv", "Generation_iv")
                        .WithOne("Diamond_Pearl")
                        .HasForeignKey("PokedexRazorPages.Models.Diamond_Pearl", "Generation_ivId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_iv");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.DreamWorld", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Other", "Other")
                        .WithOne("DreamWorld")
                        .HasForeignKey("PokedexRazorPages.Models.DreamWorld", "OtherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Other");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Emerald", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_iii", "Generation_iii")
                        .WithOne("Emerald")
                        .HasForeignKey("PokedexRazorPages.Models.Emerald", "Generation_iiiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_iii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Firered_Leafgreen", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_iii", "Generation_iii")
                        .WithOne("Firered_Leafgreen")
                        .HasForeignKey("PokedexRazorPages.Models.Firered_Leafgreen", "Generation_iiiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_iii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Forms", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithMany("Forms")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Game_Indices", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithMany("Game_Indices")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.PastTypes", "PastTypes")
                        .WithOne("Generation")
                        .HasForeignKey("PokedexRazorPages.Models.Generation", "PastTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PastTypes");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_i", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Versions", "Versions")
                        .WithOne("Generation_i")
                        .HasForeignKey("PokedexRazorPages.Models.Generation_i", "VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_ii", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Versions", "Versions")
                        .WithOne("Generation_ii")
                        .HasForeignKey("PokedexRazorPages.Models.Generation_ii", "VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_iii", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Versions", "Versions")
                        .WithOne("Generation_iii")
                        .HasForeignKey("PokedexRazorPages.Models.Generation_iii", "VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_iv", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Versions", "Versions")
                        .WithOne("Generation_iv")
                        .HasForeignKey("PokedexRazorPages.Models.Generation_iv", "VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_v", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Versions", "Versions")
                        .WithOne("Generation_v")
                        .HasForeignKey("PokedexRazorPages.Models.Generation_v", "VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_vi", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Versions", "Versions")
                        .WithOne("Generation_vi")
                        .HasForeignKey("PokedexRazorPages.Models.Generation_vi", "VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_vii", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Versions", "Versions")
                        .WithOne("Generation_vii")
                        .HasForeignKey("PokedexRazorPages.Models.Generation_vii", "VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_viii", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Versions", "Versions")
                        .WithOne("Generation_viii")
                        .HasForeignKey("PokedexRazorPages.Models.Generation_viii", "VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Gold", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_ii", "Generation_ii")
                        .WithOne("Gold")
                        .HasForeignKey("PokedexRazorPages.Models.Gold", "Generation_iiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_ii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Heartgold_Soulsilver", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_iv", "Generation_iv")
                        .WithOne("Heartgold_Soulsilver")
                        .HasForeignKey("PokedexRazorPages.Models.Heartgold_Soulsilver", "Generation_ivId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_iv");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Held_Items", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithMany("Held_Items")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Home", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Other", "Other")
                        .WithOne("Home")
                        .HasForeignKey("PokedexRazorPages.Models.Home", "OtherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Other");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Icons_vii", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_vii", "Generation_vii")
                        .WithOne("Icons_vii")
                        .HasForeignKey("PokedexRazorPages.Models.Icons_vii", "Generation_viiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_vii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Icons_viii", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_viii", "Generation_viii")
                        .WithOne("Icons_viii")
                        .HasForeignKey("PokedexRazorPages.Models.Icons_viii", "Generation_viiiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_viii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Item", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Held_Items", "Held_Items")
                        .WithOne("Item")
                        .HasForeignKey("PokedexRazorPages.Models.Item", "Held_ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Held_Items");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.ItemVersion", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Version_Details", "Version_Details")
                        .WithOne("ItemVersion")
                        .HasForeignKey("PokedexRazorPages.Models.ItemVersion", "Version_DetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version_Details");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Move", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Moves", "Moves")
                        .WithOne("Move")
                        .HasForeignKey("PokedexRazorPages.Models.Move", "MovesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moves");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Move_Learn_Method", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Version_Group_Details", "Version_Group_Details")
                        .WithOne("Move_Learn_Method")
                        .HasForeignKey("PokedexRazorPages.Models.Move_Learn_Method", "Version_Group_DetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version_Group_Details");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Moves", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithMany("Moves")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Official_Artwork", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Other", "Other")
                        .WithOne("Official_Artwork")
                        .HasForeignKey("PokedexRazorPages.Models.Official_Artwork", "OtherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Other");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Omegaruby_Alphasapphire", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_vi", "Generation_vi")
                        .WithOne("Omegaruby_Alphasapphire")
                        .HasForeignKey("PokedexRazorPages.Models.Omegaruby_Alphasapphire", "Generation_viId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_vi");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Other", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Sprites", "Sprites")
                        .WithOne("Other")
                        .HasForeignKey("PokedexRazorPages.Models.Other", "SpritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprites");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.PastTypes", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithMany("PastTypes")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokedexRazorPages.Models.Types", "Types")
                        .WithMany()
                        .HasForeignKey("TypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Platinum", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_iv", "Generation_iv")
                        .WithOne("Platinum")
                        .HasForeignKey("PokedexRazorPages.Models.Platinum", "Generation_ivId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_iv");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Red_Blue", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_i", "Generation_i")
                        .WithOne("Red_Blue")
                        .HasForeignKey("PokedexRazorPages.Models.Red_Blue", "Generation_iId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_i");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Ruby_Sapphire", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_iii", "Generation_iii")
                        .WithOne("Ruby_Sapphire")
                        .HasForeignKey("PokedexRazorPages.Models.Ruby_Sapphire", "Generation_iiiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_iii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Silver", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_ii", "Generation_ii")
                        .WithOne("Silver")
                        .HasForeignKey("PokedexRazorPages.Models.Silver", "Generation_iiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_ii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Species", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithOne("Species")
                        .HasForeignKey("PokedexRazorPages.Models.Species", "PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Sprites", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithOne("Sprites")
                        .HasForeignKey("PokedexRazorPages.Models.Sprites", "PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Stat", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Stats", "Stats")
                        .WithOne("Stat")
                        .HasForeignKey("PokedexRazorPages.Models.Stat", "StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Stats", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithMany("Stats")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Type", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Types", "Types")
                        .WithOne("Type")
                        .HasForeignKey("PokedexRazorPages.Models.Type", "TypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Types");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Types", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithMany("Types")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Ultra_Sun_Ultra_Moon", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_vii", "Generation_vii")
                        .WithOne("Ultra_Sun_Ultra_Moon")
                        .HasForeignKey("PokedexRazorPages.Models.Ultra_Sun_Ultra_Moon", "Generation_viiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_vii");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Version", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Game_Indices", "Game_Indices")
                        .WithOne("Version")
                        .HasForeignKey("PokedexRazorPages.Models.Version", "Game_IndicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game_Indices");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Version_Details", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Held_Items", "Held_Items")
                        .WithMany("Version_Details")
                        .HasForeignKey("Held_ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Held_Items");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Version_Group", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Version_Group_Details", "Version_Group_Details")
                        .WithOne("Version_Group")
                        .HasForeignKey("PokedexRazorPages.Models.Version_Group", "Version_Group_DetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version_Group_Details");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Version_Group_Details", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Moves", "Moves")
                        .WithMany("Version_Group_Details")
                        .HasForeignKey("MovesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moves");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Versions", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Sprites", "Sprites")
                        .WithOne("Versions")
                        .HasForeignKey("PokedexRazorPages.Models.Versions", "SpritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprites");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.X_Y", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_vi", "Generation_vi")
                        .WithOne("X_Y")
                        .HasForeignKey("PokedexRazorPages.Models.X_Y", "Generation_viId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_vi");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Yellow", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Generation_i", "Generation_i")
                        .WithOne("Yellow")
                        .HasForeignKey("PokedexRazorPages.Models.Yellow", "Generation_iId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation_i");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Abilities", b =>
                {
                    b.Navigation("Abilitys");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Black_White", b =>
                {
                    b.Navigation("Animated")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Game_Indices", b =>
                {
                    b.Navigation("Version")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_i", b =>
                {
                    b.Navigation("Red_Blue")
                        .IsRequired();

                    b.Navigation("Yellow")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_ii", b =>
                {
                    b.Navigation("Crystal")
                        .IsRequired();

                    b.Navigation("Gold")
                        .IsRequired();

                    b.Navigation("Silver")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_iii", b =>
                {
                    b.Navigation("Emerald")
                        .IsRequired();

                    b.Navigation("Firered_Leafgreen")
                        .IsRequired();

                    b.Navigation("Ruby_Sapphire")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_iv", b =>
                {
                    b.Navigation("Diamond_Pearl")
                        .IsRequired();

                    b.Navigation("Heartgold_Soulsilver")
                        .IsRequired();

                    b.Navigation("Platinum")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_v", b =>
                {
                    b.Navigation("Black_White")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_vi", b =>
                {
                    b.Navigation("Omegaruby_Alphasapphire")
                        .IsRequired();

                    b.Navigation("X_Y")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_vii", b =>
                {
                    b.Navigation("Icons_vii")
                        .IsRequired();

                    b.Navigation("Ultra_Sun_Ultra_Moon")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Generation_viii", b =>
                {
                    b.Navigation("Icons_viii")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Held_Items", b =>
                {
                    b.Navigation("Item")
                        .IsRequired();

                    b.Navigation("Version_Details");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Moves", b =>
                {
                    b.Navigation("Move")
                        .IsRequired();

                    b.Navigation("Version_Group_Details");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Other", b =>
                {
                    b.Navigation("DreamWorld")
                        .IsRequired();

                    b.Navigation("Home")
                        .IsRequired();

                    b.Navigation("Official_Artwork")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.PastTypes", b =>
                {
                    b.Navigation("Generation")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Pokemon", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Forms");

                    b.Navigation("Game_Indices");

                    b.Navigation("Held_Items");

                    b.Navigation("Moves");

                    b.Navigation("PastTypes");

                    b.Navigation("Species")
                        .IsRequired();

                    b.Navigation("Sprites")
                        .IsRequired();

                    b.Navigation("Stats");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Sprites", b =>
                {
                    b.Navigation("Other")
                        .IsRequired();

                    b.Navigation("Versions")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Stats", b =>
                {
                    b.Navigation("Stat")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Types", b =>
                {
                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Version_Details", b =>
                {
                    b.Navigation("ItemVersion")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Version_Group_Details", b =>
                {
                    b.Navigation("Move_Learn_Method")
                        .IsRequired();

                    b.Navigation("Version_Group")
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Versions", b =>
                {
                    b.Navigation("Generation_i")
                        .IsRequired();

                    b.Navigation("Generation_ii")
                        .IsRequired();

                    b.Navigation("Generation_iii")
                        .IsRequired();

                    b.Navigation("Generation_iv")
                        .IsRequired();

                    b.Navigation("Generation_v")
                        .IsRequired();

                    b.Navigation("Generation_vi")
                        .IsRequired();

                    b.Navigation("Generation_vii")
                        .IsRequired();

                    b.Navigation("Generation_viii")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
