// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokedexRazorPages.Data;

#nullable disable

namespace PokedexRazorPages.Migrations
{
    [DbContext(typeof(PokedexRazorPagesContext))]
    [Migration("20230816142757_Experimental Db")]
    partial class ExperimentalDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokedexRazorPages.Models.AbilityObj", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PokemonId"));

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("PokemonId1")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.HasIndex("PokemonId1");

                    b.ToTable("AbilityObj");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.SpriteObj", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.ToTable("SpriteObj");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.TypeObj", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PokemonId"));

                    b.Property<int>("PokemonId1")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.HasIndex("PokemonId1");

                    b.ToTable("TypeObj");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.AbilityObj", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithMany("Abilities")
                        .HasForeignKey("PokemonId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.SpriteObj", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithOne("Sprites")
                        .HasForeignKey("PokedexRazorPages.Models.SpriteObj", "PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.TypeObj", b =>
                {
                    b.HasOne("PokedexRazorPages.Models.Pokemon", "Pokemon")
                        .WithMany("Types")
                        .HasForeignKey("PokemonId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokedexRazorPages.Models.Pokemon", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Sprites")
                        .IsRequired();

                    b.Navigation("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
